default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: make_software_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: make_software_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: make_software_production
  username: make_software
  password: <%= ENV['MAKE_SOFTWARE_DATABASE_PASSWORD'] %>
